hmac_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
enforce_signatures = true
report_dir = "./reports"

[repos.foo]
path = "./repos/bar"
entrypoint = ".minicycle/entrypoint"
branches = ["main", "premain"]

[repos.bar]
path = "./repos/bar"
entrypoint = ".minicycle/entrypoint"
branches = ["main"]



