hmac_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
enforce_signatures = true
report_dir = "./reports"

[repos.foo]
path = "./repos/bar"
entrypoint = ".minicycle/entrypoint"

[repos.bar]
path = "./repos/bar"
entrypoint = ".minicycle/entrypoint"



