hmac_key = "syEXRxCEfGz37sdby4QdChzRKQn3xwbN4xUdIrHFCU2IRX4NqcBNUAtWh5DEA7JD"
enforce_signatures = true

[repos.foo]
name = "foo"
path = "./tmp/bar"
entrypoint = ".minicycle/entrypoint"

[repos.bar]
name = "foo"
path = "./tmp/bar"
entrypoint = ".minicycle/entrypoint"



